type User @table {
  displayName: String!
  createdAt: Timestamp! @default(expr: "request.time")
  email: String
  photoUrl: String
}

# Renamed to CadModel to satisfy linter
type CadModel @table {
  name: String!
  createdAt: Timestamp! @default(expr: "request.time")
  updatedAt: Timestamp! @default(expr: "request.time")
  modelData: String!
  isPublic: Boolean!
  description: String
  promptUsed: String
  thumbnailUrl: String
  owner: User
  project: Project
}

type Prompt @table {
  text: String!
  createdAt: Timestamp! @default(expr: "request.time")
  feedback: String
  user: User
  modelGenerated: CadModel
}

type Project @table {
  name: String!
  createdAt: Timestamp! @default(expr: "request.time")
  updatedAt: Timestamp! @default(expr: "request.time")
  description: String
  owner: User
}

type Feedback @table {
  rating: Int!
  createdAt: Timestamp! @default(expr: "request.time")
  comments: String
  type: String
  user: User
  cadModel: CadModel
  prompt: Prompt
}